platform :ios, "7.0"

pod 'MBProgressHUD', '0.8'
pod 'AFNetworking', '2.5.3'
pod 'JSONModel', '1.0.0'
pod 'TPKeyboardAvoiding'
pod 'UIAlertView+Block', '1.1.0'
pod 'SSPullToRefresh', '1.2.0'
pod 'UICKeyChainStore', '2.0.6'
pod 'UIDevice-Hardware'
pod 'RNCryptor', '3.0.1'
pod 'TWMessageBarManager'
